const LOGGED_IN = 'LOGGED_IN';
const LOGGED_OUT = 'LOGGED_OUT';
const REGISTER_USER = 'REGISTER_USER';
const SELECT_EVENT = 'SELECT_EVENT';

module.exports = {
    LOGGED_IN,
    LOGGED_OUT,
    REGISTER_USER,
    SELECT_EVENT
};