const EMPLOYEE_LOGGED_IN = 'EMPLOYEE_LOGGED_IN';
const EMPLOYER_LOGGED_IN = 'EMPLOYER_LOGGED_IN';
const LOGGED_OUT = 'LOGGED_OUT';
const REGISTER_EMPLOYEE = 'REGISTER_EMPLOYEE';
const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
const CREATE_JOB = 'CREATE_JOB';

module.exports = {
    EMPLOYEE_LOGGED_IN,
    EMPLOYER_LOGGED_IN,
    LOGGED_OUT,
    REGISTER_EMPLOYEE,
    UPDATE_EMPLOYEE,
    CREATE_JOB
};